apiVersion: batch/v1
kind: Job
metadata:
  name: go-trace-generator
  namespace: default
spec:
  template:
    spec:
      containers:
      - name: trace-app
        image: hardik0811/otel-jaegar
      restartPolicy: Never
  backoffLimit: 1
